spring:
  application:
    name: FlowSync

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: system
    password: Password123
    driver-class-name: oracle.jdbc.OracleDriver

  jdbc:
    template:
      query-timeout: 30

logging:
  file:
    name: logs/app.log

jwt:
  secret: mySecretKeyForJwtAuthenticationMySecretKey123456
  expiration: 86400000